// File generated by FlutterFire CLI (placeholder for DonationChain).
// Replace by running: flutterfire configure
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  // --- REPLACE THESE WITH YOUR REAL FIREBASE PROJECT VALUES ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY_WEB_KEY_REPLACE_ME',
    appId: '1:000000000000:web:abcdef123456',
    messagingSenderId: '000000000000',
    projectId: 'donationchain-demo',
    authDomain: 'donationchain-demo.firebaseapp.com',
    storageBucket: 'donationchain-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY_ANDROID_KEY_REPLACE_ME',
    appId: '1:000000000000:android:abcdef123456',
    messagingSenderId: '000000000000',
    projectId: 'donationchain-demo',
    storageBucket: 'donationchain-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY_IOS_KEY_REPLACE_ME',
    appId: '1:000000000000:ios:abcdef123456',
    messagingSenderId: '000000000000',
    projectId: 'donationchain-demo',
    storageBucket: 'donationchain-demo.appspot.com',
    iosBundleId: 'pk.donationchain.donationchainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY_MACOS_KEY_REPLACE_ME',
    appId: '1:000000000000:ios:abcdef123456',
    messagingSenderId: '000000000000',
    projectId: 'donationchain-demo',
    storageBucket: 'donationchain-demo.appspot.com',
    iosBundleId: 'pk.donationchain.donationchainApp',
  );
}
